
apiVersion: v1
kind: Service
metadata:
  name: poorna-service
spec:
  type: NodePort
  selector:
    app: poorna
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080    # Must be within clusterâ€™s allowed range (default 30000-327
